%BRAPH 2 for MemoryCapacity.

braph2

if ispc
    fprintf([ ...
        '\n' ...
        '<strong>Ø   Ø   ØØØØØ  \n</strong>' ... 
        '<strong>ØØ ØØ   Ø      \n</strong>' ...
        '<strong>Ø Ø Ø   Ø      \n</strong>' ...
        '<strong>Ø   Ø   Ø      \n</strong>' ...
        '<strong>Ø   Ø @ ØØØØØ @\n</strong>' ...
        '\n' ...
        ]);
else
    fprintf([ ...
        '\n' ...
        ' █   █   █████  \n' ...
        ' ██ ██   █      \n' ...
        ' █ █ █   █      \n' ...
        ' █   █   █      \n' ...
        ' █   █ █ █████ █\n' ...
        '\n' ...
        ]);
end

fprintf([ ...
    '\n' ...
    ' <a href="matlab:a_con = ; gui = GUIElement(''PE'', a_con, ''WAITBAR'', true); gui.get(''DRAW''); gui.get(''SHOW'');">Open Memory Capacity Analysis</a>\n' ...
    '\n' ...
    ])